apiVersion: obs-api.observatorium.io/v1alpha1
kind: Observatorium
metadata:
  name: observatorium-sample
spec:
  thanos:
    image: quay.io/thanos/thanos
    version: v0.9.0
    objectStoreConfigKey: thanos.yaml
    objectStoreConfigSecret: thanos-objectstorage
    hashrings:
      - hashring: hashring0
        tenants:
          - foo
          - bar
      - hashring: default
        tenants: []
    querier:
      replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
    queryCache:
      image: quay.io/cortexproject/cortex
      version: master-8533a216
      replicas: 1
    store:
      pvcSpec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
    compact:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
    rule:
      pvcSpec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
    receivers:
      pvcSpec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
    receiveController:
      image: quay.io/observatorium/thanos-receive-controller
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 24Mi
        limits:
          cpu: 64m
          memory: 128Mi